spring:
  datasource:
    username: root
    password: yroot
    url: jdbc:mysql://localhost:3306/friend?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver

